// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200613205453_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstPlayerElement")
                        .IsRequired()
                        .HasColumnName("first_player_element")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("FirstPlayerName")
                        .IsRequired()
                        .HasColumnName("first_player_name")
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("GameDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("game_date")
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("GameResult")
                        .IsRequired()
                        .HasColumnName("game_result")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SecondPlayerElement")
                        .IsRequired()
                        .HasColumnName("second_player_element")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SecondPlayerName")
                        .IsRequired()
                        .HasColumnName("second_player")
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("history");
                });
#pragma warning restore 612, 618
        }
    }
}
